package Ventanas;

import logica.*;

public class InterfazEstacionesConcurridas extends javax.swing.JFrame {
    private MenuInicial menuInicial;
    private SimuladorConcurrencia simulador;
    private int[] claves;  
    private javax.swing.JButton BotonVolver;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoMapa;
    private javax.swing.JLabel PersonasAlameda;
    private javax.swing.JLabel PersonasCDLTorre;
    private javax.swing.JLabel PersonasCarolina;
    private javax.swing.JLabel PersonasEjido;
    private javax.swing.JLabel PersonasIñaquito;
    private javax.swing.JLabel PersonasJipijapa;
    private javax.swing.JLabel PersonasLabrador;
    private javax.swing.JLabel PersonasMagdalena;
    private javax.swing.JLabel PersonasMoranValverde;
    private javax.swing.JLabel PersonasPradera;
    private javax.swing.JLabel PersonasQuitumbe;
    private javax.swing.JLabel PersonasRecreo;
    private javax.swing.JLabel PersonasSanFrancisco;
    private javax.swing.JLabel PersonasSolanda;
    private javax.swing.JLabel PersonasUCentral;
    private javax.swing.JLabel TagAlameda;
    private javax.swing.JLabel TagCDLTorres;
    private javax.swing.JLabel TagCarolina;
    private javax.swing.JLabel TagEjido;
    private javax.swing.JLabel TagIñaquito;
    private javax.swing.JLabel TagJipijapa;
    private javax.swing.JLabel TagLabrador;
    private javax.swing.JLabel TagMValverde;
    private javax.swing.JLabel TagMagdalena;
    private javax.swing.JLabel TagPradera;
    private javax.swing.JLabel TagQuitumbre;
    private javax.swing.JLabel TagRecreo;
    private javax.swing.JLabel TagSanFrancisco;
    private javax.swing.JLabel TagSolanda;
    private javax.swing.JLabel TagUniCentral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAmarrillo;
    private javax.swing.JPanel jPanelAzul;
    private javax.swing.JPanel jPanelRojo;
    
    public InterfazEstacionesConcurridas(MenuInicial menuInicial, Servicio simuladorConcurrencia) {
        this.menuInicial = menuInicial;
        this.simulador = (SimuladorConcurrencia) simuladorConcurrencia;
        this.claves = new int[]{202301,202302,202303,202304,202305,202306,202307,202308,202309,202310,
                       202311,202312,202313,202314,202315};
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelAmarrillo = new javax.swing.JPanel();
        jPanelAzul = new javax.swing.JPanel();
        jPanelRojo = new javax.swing.JPanel();
        BotonVolver = new javax.swing.JButton();
        TagQuitumbre = new javax.swing.JLabel();
        PersonasQuitumbe = new javax.swing.JLabel();
        TagMValverde = new javax.swing.JLabel();
        PersonasMoranValverde = new javax.swing.JLabel();
        TagSolanda = new javax.swing.JLabel();
        PersonasSolanda = new javax.swing.JLabel();
        TagCDLTorres = new javax.swing.JLabel();
        PersonasCDLTorre = new javax.swing.JLabel();
        TagMagdalena = new javax.swing.JLabel();
        PersonasMagdalena = new javax.swing.JLabel();
        TagAlameda = new javax.swing.JLabel();
        PersonasAlameda = new javax.swing.JLabel();
        TagEjido = new javax.swing.JLabel();
        PersonasEjido = new javax.swing.JLabel();
        TagSanFrancisco = new javax.swing.JLabel();
        PersonasSanFrancisco = new javax.swing.JLabel();
        TagUniCentral = new javax.swing.JLabel();
        PersonasUCentral = new javax.swing.JLabel();
        TagCarolina = new javax.swing.JLabel();
        PersonasCarolina = new javax.swing.JLabel();
        TagPradera = new javax.swing.JLabel();
        PersonasPradera = new javax.swing.JLabel();
        TagIñaquito = new javax.swing.JLabel();
        PersonasIñaquito = new javax.swing.JLabel();
        TagJipijapa = new javax.swing.JLabel();
        PersonasJipijapa = new javax.swing.JLabel();
        TagRecreo = new javax.swing.JLabel();
        PersonasRecreo = new javax.swing.JLabel();
        TagLabrador = new javax.swing.JLabel();
        PersonasLabrador = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        FondoMapa = new javax.swing.JLabel();
        FondoBlanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo&Eslogan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanelAmarrillo.setBackground(new java.awt.Color(237, 237, 0));

        javax.swing.GroupLayout jPanelAmarrilloLayout = new javax.swing.GroupLayout(jPanelAmarrillo);
        jPanelAmarrillo.setLayout(jPanelAmarrilloLayout);
        jPanelAmarrilloLayout.setHorizontalGroup(
            jPanelAmarrilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelAmarrilloLayout.setVerticalGroup(
            jPanelAmarrilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelAmarrillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 800, 10));

        jPanelAzul.setBackground(new java.awt.Color(0, 51, 153));

        javax.swing.GroupLayout jPanelAzulLayout = new javax.swing.GroupLayout(jPanelAzul);
        jPanelAzul.setLayout(jPanelAzulLayout);
        jPanelAzulLayout.setHorizontalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanelAzulLayout.setVerticalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 210, 10));

        jPanelRojo.setBackground(new java.awt.Color(153, 0, 51));
        jPanelRojo.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanelRojoLayout = new javax.swing.GroupLayout(jPanelRojo);
        jPanelRojo.setLayout(jPanelRojoLayout);
        jPanelRojoLayout.setHorizontalGroup(
            jPanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanelRojoLayout.setVerticalGroup(
            jPanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, 230, 10));

        BotonVolver.setBackground(new java.awt.Color(0, 0, 0));
        BotonVolver.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        BotonVolver.setText("Volver");
        BotonVolver.setBorderPainted(false);
        BotonVolver.setContentAreaFilled(false);
        BotonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVolver.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        BotonVolver.setHideActionText(true);
        BotonVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BotonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, -1, 20));

        TagQuitumbre.setBackground(new java.awt.Color(255, 255, 255));
        TagQuitumbre.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagQuitumbre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagQuitumbre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoRojo.png"))); // NOI18N
        TagQuitumbre.setText("QUITUMBE");
        TagQuitumbre.setToolTipText("");
        TagQuitumbre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagQuitumbre.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(TagQuitumbre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, 50));

        PersonasQuitumbe.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasQuitumbe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasQuitumbe.setText(simulador.getNumeroDePersonas(claves[0]));
        getContentPane().add(PersonasQuitumbe, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 70, -1));

        TagMValverde.setBackground(new java.awt.Color(255, 255, 255));
        TagMValverde.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagMValverde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagMValverde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoVerde.png"))); // NOI18N
        TagMValverde.setText("MORÁN VALVERDE");
        TagMValverde.setToolTipText("");
        TagMValverde.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagMValverde.setVerifyInputWhenFocusTarget(false);
        TagMValverde.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(TagMValverde, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 180, 50));

        PersonasMoranValverde.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasMoranValverde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasMoranValverde.setText(simulador.getNumeroDePersonas(claves[1]));
        getContentPane().add(PersonasMoranValverde, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 70, -1));

        TagSolanda.setBackground(new java.awt.Color(255, 255, 255));
        TagSolanda.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagSolanda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagSolanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoMorado.png"))); // NOI18N
        TagSolanda.setText("SOLANDA");
        TagSolanda.setToolTipText("");
        TagSolanda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagSolanda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(TagSolanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 120, 50));

        PersonasSolanda.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasSolanda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasSolanda.setText(simulador.getNumeroDePersonas(claves[2]));
        getContentPane().add(PersonasSolanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 70, -1));

        TagCDLTorres.setBackground(new java.awt.Color(255, 255, 255));
        TagCDLTorres.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagCDLTorres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagCDLTorres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoVerde.png"))); // NOI18N
        TagCDLTorres.setText("CARDENAL \nDE LA TORRE");
        TagCDLTorres.setToolTipText("");
        TagCDLTorres.setAlignmentY(40.0F);
        TagCDLTorres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagCDLTorres.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(TagCDLTorres, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 240, 60));

        PersonasCDLTorre.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasCDLTorre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasCDLTorre.setText(simulador.getNumeroDePersonas(claves[2]));
        getContentPane().add(PersonasCDLTorre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 70, -1));

        TagMagdalena.setBackground(new java.awt.Color(255, 255, 255));
        TagMagdalena.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagMagdalena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagMagdalena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoRojo.png"))); // NOI18N
        TagMagdalena.setText("MAGDALENA");
        TagMagdalena.setToolTipText("");
        TagMagdalena.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagMagdalena.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(TagMagdalena, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 150, 50));

        PersonasMagdalena.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasMagdalena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasMagdalena.setText(simulador.getNumeroDePersonas(claves[3]));
        getContentPane().add(PersonasMagdalena, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 70, -1));

        TagAlameda.setBackground(new java.awt.Color(255, 255, 255));
        TagAlameda.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagAlameda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagAlameda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoRojo.png"))); // NOI18N
        TagAlameda.setText("ALAMEDA");
        TagAlameda.setToolTipText("");
        TagAlameda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagAlameda.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(TagAlameda, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 120, 50));

        PersonasAlameda.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasAlameda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasAlameda.setText(simulador.getNumeroDePersonas(claves[4]));
        getContentPane().add(PersonasAlameda, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 70, -1));

        TagEjido.setBackground(new java.awt.Color(255, 255, 255));
        TagEjido.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagEjido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagEjido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoVerde.png"))); // NOI18N
        TagEjido.setText("EJIDO");
        TagEjido.setToolTipText("");
        TagEjido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagEjido.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(TagEjido, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 150, 50));

        PersonasEjido.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasEjido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasEjido.setText(simulador.getNumeroDePersonas(claves[5]));
        getContentPane().add(PersonasEjido, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 70, -1));

        TagSanFrancisco.setBackground(new java.awt.Color(255, 255, 255));
        TagSanFrancisco.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagSanFrancisco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagSanFrancisco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoAzul.png"))); // NOI18N
        TagSanFrancisco.setText("SAN FRANCISCO");
        TagSanFrancisco.setToolTipText("");
        TagSanFrancisco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagSanFrancisco.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(TagSanFrancisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 150, 50));

        PersonasSanFrancisco.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasSanFrancisco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasSanFrancisco.setText(simulador.getNumeroDePersonas(claves[6]));
        getContentPane().add(PersonasSanFrancisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 70, -1));

        TagUniCentral.setBackground(new java.awt.Color(255, 255, 255));
        TagUniCentral.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagUniCentral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagUniCentral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoAzul.png"))); // NOI18N
        TagUniCentral.setText("UNIVERSIDAD CENTRAL");
        TagUniCentral.setToolTipText("");
        TagUniCentral.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagUniCentral.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(TagUniCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 240, 50));

        PersonasUCentral.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasUCentral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasUCentral.setText(simulador.getNumeroDePersonas(claves[7]));
        getContentPane().add(PersonasUCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 70, -1));

        TagCarolina.setBackground(new java.awt.Color(255, 255, 255));
        TagCarolina.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagCarolina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagCarolina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoVerde.png"))); // NOI18N
        TagCarolina.setText("CAROLINA");
        TagCarolina.setToolTipText("");
        TagCarolina.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagCarolina.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(TagCarolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, 140, 50));

        PersonasCarolina.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasCarolina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasCarolina.setText(simulador.getNumeroDePersonas(claves[8]));
        getContentPane().add(PersonasCarolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, 70, -1));

        TagPradera.setBackground(new java.awt.Color(255, 255, 255));
        TagPradera.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagPradera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagPradera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoRojo.png"))); // NOI18N
        TagPradera.setText("PRADERA");
        TagPradera.setToolTipText("");
        TagPradera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagPradera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(TagPradera, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 140, 50));

        PersonasPradera.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasPradera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasPradera.setText(simulador.getNumeroDePersonas(claves[9]));
        getContentPane().add(PersonasPradera, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 70, -1));

        TagIñaquito.setBackground(new java.awt.Color(255, 255, 255));
        TagIñaquito.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagIñaquito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagIñaquito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoRojo.png"))); // NOI18N
        TagIñaquito.setText("IÑAQUITO");
        TagIñaquito.setToolTipText("");
        TagIñaquito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagIñaquito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(TagIñaquito, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 350, 120, 50));

        PersonasIñaquito.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasIñaquito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasIñaquito.setText(simulador.getNumeroDePersonas(claves[10]));
        getContentPane().add(PersonasIñaquito, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, 70, -1));

        TagJipijapa.setBackground(new java.awt.Color(255, 255, 255));
        TagJipijapa.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagJipijapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagJipijapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoMorado.png"))); // NOI18N
        TagJipijapa.setText("JIPIJAPA");
        TagJipijapa.setToolTipText("");
        TagJipijapa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagJipijapa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(TagJipijapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 350, 120, 50));

        PersonasJipijapa.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasJipijapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasJipijapa.setText(simulador.getNumeroDePersonas(claves[11]));
        getContentPane().add(PersonasJipijapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 490, 70, -1));

        TagRecreo.setBackground(new java.awt.Color(255, 255, 255));
        TagRecreo.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagRecreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagRecreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoAzul.png"))); // NOI18N
        TagRecreo.setText("RECREO");
        TagRecreo.setToolTipText("");
        TagRecreo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagRecreo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(TagRecreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 140, 50));

        PersonasRecreo.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasRecreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasRecreo.setText(simulador.getNumeroDePersonas(claves[12]));
        getContentPane().add(PersonasRecreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 70, -1));

        TagLabrador.setBackground(new java.awt.Color(255, 255, 255));
        TagLabrador.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        TagLabrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagLabrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CirculoRojo.png"))); // NOI18N
        TagLabrador.setText("LABRADOR");
        TagLabrador.setToolTipText("");
        TagLabrador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TagLabrador.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(TagLabrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 280, 140, 50));

        PersonasLabrador.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        PersonasLabrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PersonasLabrador.setText(simulador.getNumeroDePersonas(claves[13]));
        getContentPane().add(PersonasLabrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 150, 70, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaArriba.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 200, 70, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaArriba.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 70, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaAbajo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 400, 70, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaArriba.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 70, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaArriba.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 70, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaArriba.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 70, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaArriba.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 70, 80));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaArriba.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 70, 80));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaArriba.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, 70, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pasajeros");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 70, 40));
        jLabel2.getAccessibleContext().setAccessibleName("50 \\n\nPasajeros\n");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Pasajeros");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 70, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Pasajeros");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 70, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Pasajeros");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 70, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Pasajeros");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 70, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Pasajeros");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 70, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Pasajeros");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 70, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Pasajeros");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 70, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Pasajeros");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 70, 40));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaArriba.png"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 70, 80));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaAbajo.png"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 70, 80));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaAbajo.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 70, 80));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaAbajo.png"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 70, 80));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaAbajo.png"))); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 390, 70, 80));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaAbajo.png"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 400, 70, 80));

        jLabel26.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Pasajeros");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 160, 70, 40));

        jLabel27.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Pasajeros");
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 500, 70, 40));

        jLabel28.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Pasajeros");
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 500, 70, 40));

        jLabel29.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Pasajeros");
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 70, 40));

        jLabel30.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Pasajeros");
        jLabel30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 70, 40));

        jLabel31.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Pasajeros");
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 70, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, -1, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, -1, -1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 480, -1, -1));

        jPanel13.setBackground(new java.awt.Color(255, 255, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 480, -1, -1));

        jPanel14.setBackground(new java.awt.Color(255, 255, 204));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 140, -1, -1));

        jPanel15.setBackground(new java.awt.Color(255, 255, 204));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, -1, -1));

        FondoMapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MapaQuito.jpg"))); // NOI18N
        getContentPane().add(FondoMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1230, 510));

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Blanco.jpg"))); // NOI18N
        FondoBlanco.setText("jLabelFondoBlanco");
        FondoBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 2));
        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 630));

        pack();
    }// </editor-fold>                        

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {                                            
        menuInicial.setVisible(true); // Muestra el MenuInicial
        this.dispose(); // Cierra la ventana actual (Boleteria)
    }                                           
                               
}
