/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import logica.Boletería;

/**
 *
 * @author Gabriel
 */
public class InterfazSeleccionDeTickets extends javax.swing.JFrame {

    private Boletería boleteria;
    private String estacion;
    private String edadSeleccionada;

    /**
     * Creates new form InterfazSeleccionDeTickets
     */
    public InterfazSeleccionDeTickets(Boletería boleteria) {
        initComponents();
        this.boleteria = boleteria;
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
        this.setVisible(true);

        botonConfirmar.addActionListener(e -> {
            String edadSeleccionada = (String) CajaEdad.getSelectedItem();
            String estacion = (String) CajaEstaciones.getSelectedItem();
            confirmado(true, edadSeleccionada, estacion);
        });
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Metro_de_Quito.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTicket = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CajaEdad = new javax.swing.JComboBox<>();
        CajaEstaciones = new javax.swing.JComboBox<>();
        TextoEstacion = new javax.swing.JLabel();
        FotoEncabezado = new javax.swing.JLabel();
        TextoEdad = new javax.swing.JLabel();
        botonConfirmar = new javax.swing.JButton();
        ImagenFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelTicket.setBackground(new java.awt.Color(255, 255, 255));
        PanelTicket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        PanelTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Encabezado.setBackground(new java.awt.Color(221, 87, 87));

        jLabel1.setBackground(new java.awt.Color(204, 204, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Tickets ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CajaEdad.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        CajaEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niño", "Adulto", "Estudiante", "Adulto Mayor" }));
        CajaEdad.setBorder(null);
        CajaEdad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CajaEdad.setLightWeightPopupEnabled(false);

        CajaEstaciones.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        CajaEstaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QUITUMBE", "MORANVALVERDE", "SOLANDA", "CARDENALDELATORRE", "RECREO", "MAGDALENA", "SANFRANCISCO", "ALADEMA", "EJIDO", "UNIVERSIDADCENTRAL", "PRADERA", "CAROLINA", "IÑAQUITO", "JIPIJAPA", "LABRADOR" }));
        CajaEstaciones.setBorder(null);
        CajaEstaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CajaEstaciones.setLightWeightPopupEnabled(false);

        TextoEstacion.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        TextoEstacion.setText("Selecciona la estación:");

        FotoEncabezado.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        FotoEncabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TicketLogo.png"))); // NOI18N
        FotoEncabezado.setText("TICKET");

        TextoEdad.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        TextoEdad.setText("Selecciona la edad:");

        botonConfirmar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        botonConfirmar.setText("CONFIRMAR");
        botonConfirmar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonConfirmar.setContentAreaFilled(false);
        botonConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTicketLayout = new javax.swing.GroupLayout(PanelTicket);
        PanelTicket.setLayout(PanelTicketLayout);
        PanelTicketLayout.setHorizontalGroup(
            PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTicketLayout.createSequentialGroup()
                .addGroup(PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelTicketLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Encabezado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelTicketLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(FotoEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelTicketLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoEstacion)
                            .addComponent(TextoEdad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CajaEstaciones, javax.swing.GroupLayout.Alignment.TRAILING, 0, 151, Short.MAX_VALUE)
                            .addComponent(CajaEdad, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(41, 41, 41))
            .addGroup(PanelTicketLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(botonConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTicketLayout.setVerticalGroup(
            PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FotoEncabezado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoEdad))
                .addGap(35, 35, 35)
                .addGroup(PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CajaEstaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoEstacion))
                .addGap(18, 18, 18)
                .addComponent(botonConfirmar)
                .addGap(37, 37, 37))
        );

        getContentPane().add(PanelTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 360, 270));

        ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TicketFondo.jpeg"))); // NOI18N
        getContentPane().add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConfirmarActionPerformed

    public void confirmado(boolean confirmado, String edadSeleccionada, String estacionSeleccionada) {
        if (confirmado) {
            this.dispose();
            this.boleteria.guardarDatos(edadSeleccionada, estacionSeleccionada);
        }
    }

    public String getEdad() {
        return edadSeleccionada;
    }

    public String getEstacion() {
        return estacion;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CajaEdad;
    private javax.swing.JComboBox<String> CajaEstaciones;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel FotoEncabezado;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JPanel PanelTicket;
    private javax.swing.JLabel TextoEdad;
    private javax.swing.JLabel TextoEstacion;
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
