/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import logica.Boletería;
import logica.CompaniaMetrodeQuito;

/**
 *
 * @author Gabriel
 */
public class InterfazBoleteria extends javax.swing.JFrame {

    private MenuInicial menuInicial;
    private InterfazBoleteria boleteriaGUI;
    private InterfazSeleccionDeTickets tickets;

    private CompaniaMetrodeQuito empresa;
    private String textoIngresado;
    private Boletería boleteria;
    private int numeroPersonas;

    /**
     * Creates new form InterfazBoleteria
     */
    public InterfazBoleteria(MenuInicial menuInicial, CompaniaMetrodeQuito empresa) {
        this.empresa = empresa;
        this.menuInicial = menuInicial;
        this.boleteria = (Boletería) empresa.getBoleteria();
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());

    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Metro_de_Quito.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAzul = new javax.swing.JPanel();
        jPanelAmarrillo = new javax.swing.JPanel();
        jPanelRojo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelRojo1 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        cajaTextoPersonas = new javax.swing.JTextField();
        TextoPersonas = new javax.swing.JLabel();
        jPanelNegro = new javax.swing.JPanel();
        BotonVolver = new javax.swing.JButton();
        BotonObtenerDatos = new javax.swing.JButton();
        BotonAtender = new javax.swing.JButton();
        FondoBlanco = new javax.swing.JLabel();
        FondoTren = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAzul.setBackground(new java.awt.Color(0, 51, 153));

        javax.swing.GroupLayout jPanelAzulLayout = new javax.swing.GroupLayout(jPanelAzul);
        jPanelAzul.setLayout(jPanelAzulLayout);
        jPanelAzulLayout.setHorizontalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanelAzulLayout.setVerticalGroup(
            jPanelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 70, 10));

        jPanelAmarrillo.setBackground(new java.awt.Color(237, 237, 0));

        javax.swing.GroupLayout jPanelAmarrilloLayout = new javax.swing.GroupLayout(jPanelAmarrillo);
        jPanelAmarrillo.setLayout(jPanelAmarrilloLayout);
        jPanelAmarrilloLayout.setHorizontalGroup(
            jPanelAmarrilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanelAmarrilloLayout.setVerticalGroup(
            jPanelAmarrilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelAmarrillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, 10));

        jPanelRojo.setBackground(new java.awt.Color(153, 0, 51));
        jPanelRojo.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanelRojoLayout = new javax.swing.GroupLayout(jPanelRojo);
        jPanelRojo.setLayout(jPanelRojoLayout);
        jPanelRojoLayout.setHorizontalGroup(
            jPanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelRojoLayout.setVerticalGroup(
            jPanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 60, 10));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Boletería");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 260, -1));

        jPanelRojo1.setBackground(new java.awt.Color(204, 0, 102));

        javax.swing.GroupLayout jPanelRojo1Layout = new javax.swing.GroupLayout(jPanelRojo1);
        jPanelRojo1.setLayout(jPanelRojo1Layout);
        jPanelRojo1Layout.setHorizontalGroup(
            jPanelRojo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanelRojo1Layout.setVerticalGroup(
            jPanelRojo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelRojo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 260, 10));

        jLabelLogo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TaquillaLogo.png"))); // NOI18N
        jLabelLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        cajaTextoPersonas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaTextoPersonas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaTextoPersonas.setOpaque(true);
        cajaTextoPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTextoPersonasActionPerformed(evt);
            }
        });
        getContentPane().add(cajaTextoPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 110, 30));

        TextoPersonas.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        TextoPersonas.setText("Número de personas:");
        getContentPane().add(TextoPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jPanelNegro.setBackground(new java.awt.Color(255, 255, 255));

        BotonVolver.setBackground(new java.awt.Color(0, 0, 0));
        BotonVolver.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        BotonVolver.setText("    Volver");
        BotonVolver.setBorderPainted(false);
        BotonVolver.setContentAreaFilled(false);
        BotonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVolver.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        BotonVolver.setHideActionText(true);
        BotonVolver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNegroLayout = new javax.swing.GroupLayout(jPanelNegro);
        jPanelNegro.setLayout(jPanelNegroLayout);
        jPanelNegroLayout.setHorizontalGroup(
            jPanelNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNegroLayout.createSequentialGroup()
                .addGap(0, 180, Short.MAX_VALUE)
                .addComponent(BotonVolver))
        );
        jPanelNegroLayout.setVerticalGroup(
            jPanelNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNegroLayout.createSequentialGroup()
                .addComponent(BotonVolver)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 260, 20));

        BotonObtenerDatos.setBackground(new java.awt.Color(255, 255, 204));
        BotonObtenerDatos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonObtenerDatos.setText("Obtener datos");
        BotonObtenerDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonObtenerDatos.setContentAreaFilled(false);
        BotonObtenerDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonObtenerDatos.setOpaque(true);
        BotonObtenerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonObtenerDatosActionPerformed(evt);
            }
        });
        getContentPane().add(BotonObtenerDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 110, -1));

        BotonAtender.setBackground(new java.awt.Color(255, 204, 204));
        BotonAtender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonAtender.setText("Atender");
        BotonAtender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonAtender.setContentAreaFilled(false);
        BotonAtender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAtender.setFocusable(false);
        BotonAtender.setOpaque(true);
        BotonAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtenderActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAtender, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 360, 110, -1));

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Blanco.jpg"))); // NOI18N
        FondoBlanco.setText("jLabelFondoBlanco");
        FondoBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 2));
        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 280, 360));

        FondoTren.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoBoleteria.jpg"))); // NOI18N
        getContentPane().add(FondoTren, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaTextoPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTextoPersonasActionPerformed
        String textoIngresado = cajaTextoPersonas.getText();
        this.numeroPersonas = Integer.parseInt(textoIngresado);

        //this.boleteria.agregarNumeroDePersonas(textoIngresado);
        System.out.println(textoIngresado);
    }//GEN-LAST:event_cajaTextoPersonasActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        menuInicial.setVisible(true); // Muestra el MenuInicial
        this.dispose(); // Cierra la ventana actual (Boleteria)
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtenderActionPerformed
        this.boleteria.iniciar();
    }//GEN-LAST:event_BotonAtenderActionPerformed

    private void BotonObtenerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonObtenerDatosActionPerformed
        this.boleteria.ingresarDatosUsuario(numeroPersonas);
    }//GEN-LAST:event_BotonObtenerDatosActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtender;
    private javax.swing.JButton BotonObtenerDatos;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoTren;
    private javax.swing.JLabel TextoPersonas;
    private javax.swing.JTextField cajaTextoPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAmarrillo;
    private javax.swing.JPanel jPanelAzul;
    private javax.swing.JPanel jPanelNegro;
    private javax.swing.JPanel jPanelRojo;
    private javax.swing.JPanel jPanelRojo1;
    // End of variables declaration//GEN-END:variables
}
