/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import logica.Persona;

/**
 *
 * @author Gabriel
 */
public class InterfazBoleto extends javax.swing.JFrame {

    private String edadSeleccionada;
    private String estacionSeleccionada;
    private Persona usuario;

    /**
     * Creates new form InterfazBoleto
     */
    public InterfazBoleto(double precio, Persona usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario = usuario;
        textoEstacion.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        textoEstacion.setText("->" + usuario.obtenerNombreEstacion());

        textoEdad.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        textoEdad.setText(usuario.getEdad() + "->" + precio);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Metro_de_Quito.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTicket = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LogoTicket = new javax.swing.JLabel();
        textoEstacion = new javax.swing.JLabel();
        textoEdad = new javax.swing.JLabel();
        BotonConfirmar = new javax.swing.JButton();
        FotoQR = new javax.swing.JLabel();
        Railes1 = new javax.swing.JLabel();
        Railes2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelTicket.setBackground(new java.awt.Color(255, 255, 255));
        PanelTicket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PanelTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Titulo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Metro de Quito");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        LogoTicket.setForeground(new java.awt.Color(255, 255, 255));
        LogoTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Metro_de_Quito_Pequeño.png"))); // NOI18N
        LogoTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        textoEstacion.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        textoEstacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoEstacion.setText("Selecciona la estación:");
        textoEstacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        textoEdad.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        textoEdad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoEdad.setText("Selecciona la edad:");
        textoEdad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BotonConfirmar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        BotonConfirmar.setText("CONFIRMAR");
        BotonConfirmar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonConfirmar.setContentAreaFilled(false);
        BotonConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfirmarActionPerformed(evt);
            }
        });

        FotoQR.setForeground(new java.awt.Color(255, 255, 255));
        FotoQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/QR.png"))); // NOI18N
        FotoQR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Railes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vias.jpg"))); // NOI18N

        Railes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vias.jpg"))); // NOI18N

        javax.swing.GroupLayout PanelTicketLayout = new javax.swing.GroupLayout(PanelTicket);
        PanelTicket.setLayout(PanelTicketLayout);
        PanelTicketLayout.setHorizontalGroup(
            PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTicketLayout.createSequentialGroup()
                .addGroup(PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTicketLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Railes1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTicketLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelTicketLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(LogoTicket))
                            .addGroup(PanelTicketLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoEstacion, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textoEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelTicketLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(FotoQR))))
                    .addGroup(PanelTicketLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(BotonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTicketLayout.createSequentialGroup()
                    .addContainerGap(269, Short.MAX_VALUE)
                    .addComponent(Railes2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(7, 7, 7)))
        );
        PanelTicketLayout.setVerticalGroup(
            PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTicketLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Railes1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelTicketLayout.createSequentialGroup()
                        .addComponent(LogoTicket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoEdad)
                        .addGap(18, 18, 18)
                        .addComponent(textoEstacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FotoQR)))
                .addGap(12, 12, 12))
            .addGroup(PanelTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTicketLayout.createSequentialGroup()
                    .addContainerGap(44, Short.MAX_VALUE)
                    .addComponent(Railes2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(32, 32, 32)))
        );

        getContentPane().add(PanelTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConfirmarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BotonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConfirmar;
    private javax.swing.JLabel FotoQR;
    private javax.swing.JLabel LogoTicket;
    private javax.swing.JPanel PanelTicket;
    private javax.swing.JLabel Railes1;
    private javax.swing.JLabel Railes2;
    private javax.swing.JPanel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel textoEdad;
    private javax.swing.JLabel textoEstacion;
    // End of variables declaration//GEN-END:variables
}
