/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import logica.CompaniaMetrodeQuito;

/**
 *
 * @author Gabriel
 */
public class MenuInicial extends javax.swing.JFrame {

    private CompaniaMetrodeQuito empresa;

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial(CompaniaMetrodeQuito empresaMetropolitana) {
        initComponents();
        this.empresa = empresaMetropolitana;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        setIconImage(getIconImage());
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Metro_de_Quito.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonEstaciones = new javax.swing.JButton();
        BotonBoleteria = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelRojo = new javax.swing.JPanel();
        jPanelAmarrillo = new javax.swing.JPanel();
        jPanelAzul1 = new javax.swing.JPanel();
        jPanelRojo1 = new javax.swing.JPanel();
        jPanelNegro = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JButton();
        FondoBlanco = new javax.swing.JLabel();
        FondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonEstaciones.setFont(new java.awt.Font("Segoe UI Semilight", 1, 10)); // NOI18N
        BotonEstaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EstacionesLogo.png"))); // NOI18N
        BotonEstaciones.setText("     ESTACIONES  ");
        BotonEstaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonEstaciones.setContentAreaFilled(false);
        BotonEstaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonEstaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstacionesActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEstaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 140, 50));

        BotonBoleteria.setFont(new java.awt.Font("Segoe UI Semilight", 1, 10)); // NOI18N
        BotonBoleteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BoleteriaLogo.png"))); // NOI18N
        BotonBoleteria.setText("   BOLETERÍA");
        BotonBoleteria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotonBoleteria.setContentAreaFilled(false);
        BotonBoleteria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBoleteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBoleteriaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBoleteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 140, 50));

        jLabelLogo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Metro_de_Quito.png"))); // NOI18N
        jLabelLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicio");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 260, -1));

        jPanelRojo.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanelRojoLayout = new javax.swing.GroupLayout(jPanelRojo);
        jPanelRojo.setLayout(jPanelRojoLayout);
        jPanelRojoLayout.setHorizontalGroup(
            jPanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelRojoLayout.setVerticalGroup(
            jPanelRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 260, 10));

        jPanelAmarrillo.setBackground(new java.awt.Color(237, 237, 0));

        javax.swing.GroupLayout jPanelAmarrilloLayout = new javax.swing.GroupLayout(jPanelAmarrillo);
        jPanelAmarrillo.setLayout(jPanelAmarrilloLayout);
        jPanelAmarrilloLayout.setHorizontalGroup(
            jPanelAmarrilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanelAmarrilloLayout.setVerticalGroup(
            jPanelAmarrilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelAmarrillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 140, 10));

        jPanelAzul1.setBackground(new java.awt.Color(0, 51, 153));

        javax.swing.GroupLayout jPanelAzul1Layout = new javax.swing.GroupLayout(jPanelAzul1);
        jPanelAzul1.setLayout(jPanelAzul1Layout);
        jPanelAzul1Layout.setHorizontalGroup(
            jPanelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanelAzul1Layout.setVerticalGroup(
            jPanelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelAzul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 70, 10));

        jPanelRojo1.setBackground(new java.awt.Color(153, 0, 51));
        jPanelRojo1.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanelRojo1Layout = new javax.swing.GroupLayout(jPanelRojo1);
        jPanelRojo1.setLayout(jPanelRojo1Layout);
        jPanelRojo1Layout.setHorizontalGroup(
            jPanelRojo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanelRojo1Layout.setVerticalGroup(
            jPanelRojo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelRojo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 60, 10));

        jPanelNegro.setBackground(new java.awt.Color(255, 255, 255));

        BotonSalir.setBackground(new java.awt.Color(0, 0, 0));
        BotonSalir.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        BotonSalir.setText(" Salir");
        BotonSalir.setBorderPainted(false);
        BotonSalir.setContentAreaFilled(false);
        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        BotonSalir.setHideActionText(true);
        BotonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNegroLayout = new javax.swing.GroupLayout(jPanelNegro);
        jPanelNegro.setLayout(jPanelNegroLayout);
        jPanelNegroLayout.setHorizontalGroup(
            jPanelNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNegroLayout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(BotonSalir)
                .addGap(5, 5, 5))
        );
        jPanelNegroLayout.setVerticalGroup(
            jPanelNegroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNegroLayout.createSequentialGroup()
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelNegro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 260, 20));

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Blanco.jpg"))); // NOI18N
        FondoBlanco.setText("jLabelFondoBlanco");
        FondoBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 280, 360));

        FondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoMenu.jpg"))); // NOI18N
        getContentPane().add(FondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEstacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstacionesActionPerformed
        InterfazEstacionesConcurridas ventanaEstaciones = new InterfazEstacionesConcurridas(this, this.empresa.getSimuladorConcurrencia()); // Corregir el constructor
        ventanaEstaciones.setVisible(true);
    }//GEN-LAST:event_BotonEstacionesActionPerformed

    private void BotonBoleteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBoleteriaActionPerformed
        InterfazBoleteria ventanaBoleteria = new InterfazBoleteria(this, this.empresa); // Corregir el constructor
        ventanaBoleteria.setVisible(true);
    }//GEN-LAST:event_BotonBoleteriaActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        this.dispose();// Cierra la ventana actual (Boletería)
    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBoleteria;
    private javax.swing.JButton BotonEstaciones;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAmarrillo;
    private javax.swing.JPanel jPanelAzul1;
    private javax.swing.JPanel jPanelNegro;
    private javax.swing.JPanel jPanelRojo;
    private javax.swing.JPanel jPanelRojo1;
    // End of variables declaration//GEN-END:variables
}
